### PR TITLE
Fixes duplicated tags issue

### LINKED ISSUE #103: Tags get duplicated on repeated clicks
Screenshot 2023-03-13 at 22 39 41

### PR DESCRIPTION
**Pull request by hansstanley**
Fixes #103

### CODE REVIEW

File: src/main/java/seedu/address/ui/body/address/PersonCard.java [hunk 1]
```diff
@@ -57,9 +59,12 @@ public void setPerson(Person person, int displayedIndex) {
         name.setText(person.getName().fullName);
         phone.setText(person.getPhone().value);
         star.setVisible(person.getIsFavorite().getFavoriteStatus());
+
+        ObservableList<Node> tagsList = tags.getChildren();
+        tagsList.clear();
```
Comment (igezt) [inline src/main/java/seedu/address/ui/body/address/PersonCard.java:64]: Just YEET the entire tagslist omo

**Review by igezt — APPROVED** [review]
A ~~bug~~ feature to be remembered for all time. LGTM
