### PR TITLE
Fixes unstable event operations

### LINKED ISSUE #250: Actual and displayed `INDEX` for events do not match
* Likely linked to #249 
* Affects tagging and untagging people
  * #239 
* In the worst case, using the same tag command `tagpersonevent pt/Alice et/1` repeatedly can eventually tag `Alice` to every event
  * Similarly, using `untagpersonevent pt/Alice et/1` repeatedly can eventually untag `Alice` from every event

### PR DESCRIPTION
**Pull request by hansstanley**
Previously, the `editevent`, `tagpersonevent`, and `untagpersonevent` commands would use `Set#remove` and `Set#add` (or `Set#removeAll` and `Set#addAll`) in sequence, which cycles the list of events, breaking the order in which they were added by the user. This causes confusion to the user as the corresponding displayed index of each event would change.

The operations to `Event` and `UniqueEventList` have been made stable.
* Fixes #250

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/UnTagEventCommand.java [hunk 1]
```diff
@@ -24,16 +24,16 @@ public class UnTagEventCommand extends Command {
...
             + ResultDisplay.formatMessage(ResultDisplay.KEYWORD_EXAMPLE,
                     COMMAND_WORD,
                     PREFIX_EVENT_TO_TAG + "1",
                     PREFIX_PERSON_TO_TAG + "John Doe")
             + ResultDisplay.formatMessage(ResultDisplay.KEYWORD_MORE_INFO,
                     "Note that the given contact name must be exact.");
-    private static final String MESSAGE_SUCCESS = "%1$s is now untagged from event %2$s";
-    private static final String MESSAGE_SUCCESS_2 = "%1$s is already untagged from event %2$s";
+    private static final String MESSAGE_SUCCESS = "%1$s is now untagged from the event indexed %2$s";
+    private static final String MESSAGE_SUCCESS_2 = "%1$s is already untagged from the event indexed %2$s";
```
Comment (igezt) [inline src/main/java/seedu/address/logic/commands/UnTagEventCommand.java:36]:
```suggestion
    private static final String MESSAGE_SUCCESS = "%1$s is now untagged from the event indexed as %2$s";
    private static final String MESSAGE_SUCCESS_2 = "%1$s is already untagged from the event indexed as %2$s";
```

Nitpick 😆

File: src/main/java/seedu/address/model/event/UniqueEventList.java [hunk 2]
```diff
@@ -111,35 +113,19 @@ private boolean eventsAreUnique(List<Event> events) {
...
-                toRemove.add(e);
-                toAdd.add(newEvent);
-            }
-        }
-        this.internalList.removeAll(toRemove);
-        this.internalList.addAll(toAdd);
+    public void deletePersonFromAllEvents(Person person) {
+        internalList.setAll(internalList.stream()
+                .map(event -> event.deleteTaggedPerson(person))
+                .collect(Collectors.toList()));
```
Comment (igezt) [inline src/main/java/seedu/address/model/event/UniqueEventList.java:119]: 👍

File: src/main/java/seedu/address/model/event/UniqueEventList.java [hunk 3]
```diff
@@ -111,35 +113,19 @@ private boolean eventsAreUnique(List<Event> events) {
...
-                Event newEvent = e.editTaggedPerson(personToEdit, editedPerson);
-                toRemove.add(e);
-                toAdd.add(newEvent);
-            }
-        }
-        this.internalList.removeAll(toRemove);
-        this.internalList.addAll(toAdd);
+        internalList.setAll(internalList.stream()
+                .map(event -> event.editTaggedPerson(personToEdit, editedPerson))
+                .collect(Collectors.toList()));
```
Comment (igezt) [inline src/main/java/seedu/address/model/event/UniqueEventList.java:128]: 👍

**Review by igezt — APPROVED** [review]
LGTM!
